#!/usr/bin/env node

import { readFileSync } from 'fs';
import { writeTailoredResumeMarkdown } from './resume-md-core.mjs';

function usage() {
  console.error(`Usage:
  node resume-md.mjs --plan <replacement-plan.json> <job-description-url|local:jds/file.md|jds/file.md|reports/file.md|jd text>
  node resume-md.mjs --plan <replacement-plan.json> --file <job-description.md>

Replacement plans are generated by career-ops resume-md mode. This script only validates and applies them.`);
}

const args = process.argv.slice(2);
let replacementPlan = null;
let remaining = [...args];

const planIdx = remaining.indexOf('--plan');
if (planIdx !== -1) {
  const planPath = remaining[planIdx + 1];
  if (!planPath) {
    usage();
    process.exit(1);
  }
  replacementPlan = JSON.parse(readFileSync(planPath, 'utf-8'));
  remaining.splice(planIdx, 2);
}

let input = remaining.join(' ').trim();

if (remaining[0] === '--file') {
  if (!remaining[1]) {
    usage();
    process.exit(1);
  }
  input = readFileSync(remaining[1], 'utf-8');
}

if (!input || !replacementPlan) {
  usage();
  process.exit(1);
}

try {
  const result = await writeTailoredResumeMarkdown({ input, replacementPlan });
  console.log(`Markdown resume: ${result.path}`);
  console.log(`Company: ${result.company}`);
  console.log(`Role: ${result.role}`);
  console.log(`final-score: ${result.finalScore}`);
  console.log(`Agent replacements applied: ${result.replacements.length}`);
} catch (err) {
  console.error(err?.message || String(err));
  process.exit(1);
}
